root_path: "/home/abrar/DTI/DTI-LM-main/datasets/luo's_dataset/"
data_path: 'data_folds/drug_coldstart/'
seq_path: 'feature/'
mapping_path: 'mapping/'
data_name: ['train_fold_1.csv', 'test_fold_1.csv']
name: 'luo'

